name: Release

on: 
  push:
    branches: [ master ]
  #pull_request:
  #  types: [ closed ]
    
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        envkey_URL: ${{ secrets.URL }}
        # envkey_RELEASE_MINOR: ${{ contains(github.event.pull_request.labels.*.name, 'Minor') }}
        envkey_RELEASE_MINOR: "oi"
        directory: scripts
      
    - name: Install packages
      run: cd scripts && yarn install
  
    - name: Create Release
      run: node release.js

